### ISSUE TITLE
IoTAManager does not handle multiple provisionings

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/iotagent-manager#115]
Multiple device provisioning requests arriving to the IoTAManager with the protocol specified in the body (as opposed to those specifiying it in the query parameter chain) are not handled appropriately: just the last device is created.

**Comment by chicco785** [comment]
it looks like this bug report can be closed

**Comment by fgalan** [comment]
I guess that fixed in PR #117 for master, so closing.
