### ISSUE TITLE
IOTAManager doesn't remove devices when UL service is deleted

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-manager#134]
It has been found during autoprovisioning e2e testing for UL (e.g. case iota00703) that the service is not properly deleted. The test teardown logic includes service deletion, e.g:

```
DEBUG >>>>>>>>>>>>>	 Data sent:     	>>>>>>>>>>>>> 
	> Comp: IOTA 
	> Method: delete 
	> Url: http://10.95.X.X:8082/iot/services 
	> Headers: {'Fiware-Service': u'f0320s031ppp', 'Fiware-ServicePath': '/f0320s031ppp', 'X-Auth-Token': 'd6a79e74710140f9af518111112f9907'}
	> Params: {'apikey': u'apikeyf0320s031ppp',
 'protocol': u'IoTA-UL',
 'resource': '/iot/d'} 
	> SENT REQUEST DATA SEEMS TO BE EMPTY 

DEBUG <<<<<<<<<<<<<<	 Data responded:	<<<<<<<<<<<<<<
	< Response code: 204
	< Headers: {'date': 'Fri, 02 Feb 2018 10:30:59 GMT', 'fiware-correlator': '3007af82-f030-4cff-bff5-6190e53536ce', 'connection': 'close', 'x-powered-by': 'Express'}
	< Empty Payload 
...
DEBUG >>>>>>>>>>>>>	 Data sent:     	>>>>>>>>>>>>> 
	> Comp: IOTA 
	> Method: delete 
	> Url: http://10.95.X.X:8082/iot/services 
	> Headers: {'Fiware-Service': u'f0320s032ppp', 'Fiware-ServicePath': '/f0320s032ppp', 'X-Auth-Token': '71ac3cce7b1111509caf23caf0e5268f'}
	> Params: {'apikey': u'apikeyf0320s032ppp',
 'protocol': u'IoTA-UL',
 'resource': '/iot/d'} 
	> SENT REQUEST DATA SEEMS TO BE EMPTY 

DEBUG <<<<<<<<<<<<<<	 Data responded:	<<<<<<<<<<<<<<
	< Response code: 204
	< Headers: {'date': 'Fri, 02 Feb 2018 10:31:09 GMT', 'fiware-correlator': 'fe51df58-4039-46f6-acfc-0676926fb21f', 'connection': 'close', 'x-powered-by': 'Express'}
	< Empty Payload 
```

But after that the test the `iotaul` database include the devices:

```
> db
iotaul
> db.devices.find({},{service:1, subservice:1, name:1,  _id:0})
{ "subservice" : "/f0320s031ppp", "service" : "f0320s031ppp", "name" : "sensor:df0320s031ppp" }
{ "subservice" : "/f0320s032ppp", "service" : "f0320s032ppp", "name" : "sensor:df0320s032ppp" }
```

Additional facts:

* The `groups` collection in `iotaul` DB is empty
* The `configurations` collection in `iotagent-manager` DB is empty
* Similar autoprovision scenarios for IOTA JSON (eg. iota00406) seems to work ok (i.e. database doesn't have any device at the end of the test) so maybe the problem is limited to the UL case.

This need to be further analysised. My analysis could be wrong in some point.

**Comment by AlvaroVega** [comment]
It would be exploded by a unit test ?

**Comment by fgalan** [comment]
I don't know how the unit test for IOTA Manager are but, but the need of a IOTA-UL could make it complicated. The steps script of iota00703 should be analyzed, considering if the steps that involve interactiong with IOTA UL could be mocked or not.

**Comment by fgalan** [comment]
Thanks for your research work @chicco785 . I understand it could be as you say, but let's hold on this issue here (because the problem was found in an interaction with IOTAManager), let's recheck and eventually merge once https://github.com/telefonicaid/iotagent-node-lib/issues/596 gets solved.

**Comment by fgalan** [comment]
Once PR https://github.com/telefonicaid/iotagent-node-lib/pull/597 has been merged, we should check if this issue is solved.

**Comment by fgalan** [comment]
I have checked that after running the test the DB is empty and no document remains, as before.

Thus, issue can be closed.
