### ISSUE TITLE
replicaSet configuration could be broken?

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-manager#162]
I have some doubt about MongoDB replica set configuration.

The module managing connection seems to be dbConn.js which exports a function for configuration:

```
exports.configureDb = configureDb;
```

That function has the following body:

```
function configureDb(callback) {
    /*jshint camelcase:false, validthis:true */
    var currentConfig = config.getConfig();

    if (!currentConfig.mongodb || !currentConfig.mongodb.host) {
        logger.fatal(context, 'No host found for MongoDB driver.');
        callback(new errors.BadConfiguration('No host found for MongoDB driver'));
    } else {
        var dbName = currentConfig.mongodb.db,
            port = currentConfig.mongodb.port || 27017,
            options = {};

        if (!currentConfig.mongodb.db) {
            dbName = DEFAULT_DB_NAME;
        }

        if (currentConfig.mongodb.replicaSet) {
            options.replset = { rs_name: currentConfig.mongodb.replicaSet };
        }

        init(config.getConfig().mongodb.host, dbName, port,
            currentConfig.username, currentConfig.password, {}, callback);
    }
}
```

It set a `options` object, where the replset configuration is set (`options.replset`). However note `options` object is not passed to the init() function, that does the actual initialization work. In fact, `options` object is neever used after the setting it!

Looking to init() signature:

```
function init(host, db, port, username, password, options, callback)
```

it seems that 6th parameter should be `options` instead of `{}` in the call inside configureDb().

This is very weird as all seems to point out that replica set cannot work... but we actually have deployments in which IOTAManager uses replica sets in MongoDB and it is working without problem.

We need to investigate this in detail.

**Comment by AlvaroVega** [comment]
this issue was fixed by https://github.com/telefonicaid/iotagent-manager/pull/187
