### ISSUE TITLE
IOTAM should return 404 (and 401) instead of 500

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-manager#167]
It seems that IOTAM returns a 500 instead of 404 when the devide is not found. For instance, in the following example +34555555555 doesn't exist.

```
curl -vvvv -H 'fiware-service: gasnatural'  -H 'fiware-servicepath: /' -H 'x-auth-token:  ...' https://iota.iotplatform.telefonica.com:8088/iot/devices/+34555555555?protocol=PDI-SMS-GASNATURAL
...
< HTTP/1.1 500 Internal Server Error
* Server nginx is not blacklisted
< Server: nginx
< Date: Fri, 11 Jan 2019 12:42:52 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 142
< Connection: keep-alive
< fiware-correlator: ...
< 
* Connection #0 to host iota.iotplatform.telefonica.com left intact
{"name":"TARGET_SERVER_ERROR","message":"There was an error redirecting the request to the target server: No valid replies from any IoTAgent"}
```

It has been observed in PRO environament with IOTA C++ (not sure if with other agents the behaviour is the same).

**Comment by fgalan** [comment]
A similar situation seems to happen when the IOTA rejects the token (e.g. due to expiration) and returns 401 to the ITOAM.

```
time=2019-02-12T10:10:33.891Z | lvl=DEBUG | corr=n/a | trans=n/a | op=IoTAManager.Redirector | msg=results [[{"statusCode":401,"body":"{\"reason\": \"The request is not well formed\"}","headers": <...>

time=2019-02-12T10:10:33.892Z | lvl=DEBUG | corr=n/a | trans=n/a | op=IoTAManager.Redirector | msg=Error [TARGET_SERVER_ERROR] handling request: There was an error redirecting the request to the target server: No valid repli es from any IoTAgent
```

But it seems IOTAM returns 500 to the caller...

**Comment by AlvaroVega** [comment]
If an error is retrieved by iotaRedirector then this error handler is converting error 400 in 500 due to backward compatibility with iotac++:

https://github.com/telefonicaid/iotagent-manager/blob/7f269e11a722b6fa92021491d50341c644bae2d9/lib/services/iotaRedirector.js#L446-L471

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-manager/pull/256
