### ISSUE TITLE
remove/disable PM2 for docker to use in openshift kubernetes

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-manager#202]
PM2 was introduced by https://github.com/telefonicaid/iotagent-manager/commit/990f859dce5a80889c690e5e498a28b7c2abe44d

PM2 uses root permissions, not desirable in openshift kubernetes

Idem for STH https://github.com/telefonicaid/fiware-sth-comet/commit/1ee84433303cad82c0729a99892d948ef41d6374 perseo-fe https://github.com/telefonicaid/perseo-fe/commit/e04a2e66cba936e4292bd30c38c1d1d751a22ee0

Proposed fix is enable or not into a docker-entrypoint:
https://github.com/telefonicaid/iotagent-ul/blob/master/docker/Dockerfile
https://github.com/telefonicaid/iotagent-ul/blob/master/docker/entrypoint.sh#L75

**Comment by fgalan** [comment]
PR #203
