### ISSUE TITLE
improve log about Cannot read property 'find' of undefined"

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-manager#232]
reported by @cesarjorgemartinez 

500 due to some iotagent is responding error

time=2021-02-25T10:32:20.834Z | lvl=ERROR | corr=7fed07de-8cdd-41a6-a796-23e2a4a84fc9 | trans=7fed07de-8cdd-41a6-a796-23e2a4a84fc9 | op=IoTAManager.Redirector | from=n/a | srv=sc_lanzarote | subsrv=/ | msg=REDIRECTION-002: Wrong status code detected [500] and body response [{"name":"TypeError","message":"Cannot read property 'find' of undefined"}] redirecting request | comp=IoTAgentManager
time=2021-02-25T10:32:20.834Z | lvl=ERROR | corr=7fed07de-8cdd-41a6-a796-23e2a4a84fc9 | trans=7fed07de-8cdd-41a6-a796-23e2a4a84fc9 | op=IoTAManager.Redirector | from=n/a | srv=sc_lanzarote | subsrv=/ | msg=The redirection ended up in error: | comp=IoTAgentManager TargetServerError {
name: 'TARGET_SERVER_ERROR',
message:
'There was an error redirecting the request to the target server: Wrong status code detected [500] and body response [{"name":"TypeError","message":"Cannot read property \'find\' of undefined"}] redirecting request',
code: 500 }
time=2021-02-25T10:32:20.834Z | lvl=DEBUG | corr=7fed07de-8cdd-41a6-a796-23e2a4a84fc9 | trans=7fed07de-8cdd-41a6-a796-23e2a4a84fc9 | op=IoTAManager.Redirector | from=n/a | srv=sc_lanzarote | subsrv=/ | msg=Error [TARGET_SERVER_ERROR] handling request: There was an error redirecting the request to the target server: Wrong status code detected [500] and body response [{"name":"TypeError","message":"Cannot read property 'find' of undefined"}] redirecting request | comp=IoTAgentManager

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/iotagent-manager/pull/233
