### ISSUE TITLE
[DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. 

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-manager#268]
This log was found in iotagent-manager logs:

(node:1) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.

**Comment by AlvaroVega** [comment]
The deprecation warning is happening due to a use of the [deprecated domain module](https://nodejs.org/docs/latest-v12.x/api/domain.html).

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/iotagent-manager/pull/327
