### ISSUE TITLE
Add `/iot/groups` routes to manager

### ISSUE THREAD

**Issue by mapedraza** [telefonicaid/iotagent-manager#270]
When merged https://github.com/telefonicaid/iotagent-node-lib/pull/1648, would be interesting to add the new alternative paths for configuring service groups to this component.

The Idea is to add the following routes:
* POST /iot/groups -> create a new configuration group
* GET /iot/groups -> get configuration group
* etc.

As an alternative (additionally) to:
* POST /iot/services -> create a new configuration group
* GET /iot/services -> get configuration group
* etc.

Original Issue: https://github.com/telefonicaid/iotagent-node-lib/issues/752

**Comment by fgalan** [comment]
I see two proxy alternatives:

1. Keep the same URL in the mappings:
    * POST IOTAMan/iot/configGroups -> POST /IOTA/iot/configGroups
    * POST IOTAMan/iot/services-> POST /IOTA/iot/services
2. Collapse to use always the no obsolete one at IOTA
    * POST IOTAMan/iot/configGroups -> IOTA/iot/configGroups
    * POST IOTAMan/iot/services-> POST IOTA/iot/configGroups

The second one could be complex if, apart from URL mapping, some transformation has to be done in the payload (I'm not sure but I suspects that /iot/configGroups and /iot/services use different root key in JSON payload).
