### ISSUE TITLE
Performance problems when login at debug level. Wrong logline.

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/iotagent-manager#294]
at 
https://github.com/telefonicaid/iotagent-manager/blob/master/lib/services/configurations.js#L96

Seems to be performance problems when login at debug level. At least the "configuration" object in every logline makes no sense and it could be too big.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-manager/pull/295
